### ISSUE TITLE
Instructions on the number of extra attributes is not updated

### ISSUE THREAD

**Issue by zptro** [HSLdevcom/helmet-ui#123]
https://github.com/HSLdevcom/helmet-ui/blob/cfdc26aea08636504691ab739fa609ff651bc1b8/docs/sijopankki.md?plain=1#L34

**Comment by johpiip** [comment]
@zptro, does the following part take into account that `--separate-emme-scenario` is specified for every scenario and it may not apply to all scenarios that are being validated? I did not catch this previously while reviewing, sorry!

https://github.com/HSLdevcom/helmet-model-system/blob/f32083ea35baf8ab9d76db59dcedc210edb2dea9/Scripts/helmet_validate_inputfiles.py#L204-L209

I mean if the call is something like:

```
C:\Users\PiippJo\Home\helmet-model-system\Scripts\helmet_validate_inputfiles.py
--log-level
DEBUG
--log-format
JSON
--baseline-data-path
C:\Users\PiippJo\Home\malliajot\01_Lahtodata\Base_input_data_Helmet41_test
--results-path
C:\Users\PiippJo\Home\malliajot\03_Tulokset
--scenario-name
test-helmet406
--emme-paths
C:\Users\PiippJo\Home\malliajot\02_Syottotiedot\v2018.emp
C:\Users\PiippJo\Home\malliajot\02_Syottotiedot\testimock.emp
--first-scenario-ids
24
21
--forecast-data-paths
C:\Users\PiippJo\Home\malliajot\helmet-model-system-v4.0.6-09-06-1625821679232\tests\test_data\Scenario_input_data\2030_test
C:\Users\PiippJo\Home\malliajot\02_Syottotiedot\2030_test
```

Then we would need something like:

```
--separate-emme-scenarios
TRUE
FALSE
```

Which looks weird.

**Comment by zptro** [comment]
This is fixed.
