### ISSUE TITLE
Enable several project options instead of global options

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-ui#134]
# Feature request

The UI should support running several models using different global options. This is already possible via the command line interface.

# Example

Simply put, if I select two Helmet scenarios to run, the first one could save its results to `C:/helmet/results_to_charlie/[scenarioname1]` and the second one could save its results to `C:/helmet/results_to_juliet/[scenarioname2]`.

Specifically in MAL impact assessment process, we wish to change the path of `helmet.py` so that we can batch-run different branches containing different sensitivity analysis scenarios.

# Options and arguments

The UI has the following global options:
- `project_path`
- `helmet_scripts_path`
- `emme_python_path`
- `basedata_path`
- `resultdata_path`

Of these, `project_path` is purely a UI option. Others have effect on the model run. The command-line call to run a model is of form `python helmet.py [...]` in which path to `python` executable is defined in `emme_python_path`, path to `helmet.py` is defined as `helmet_scripts_path/helmet.py`, and further arguments `[...]` include `basedata_path` and `resultdata_path`.

# Problems

- We need a GUI design. Should we just bring global options to scenario options? Or should the user select which project options does a scenario use? Should the user see without opening scenario options to which project does it belong to?
- When the UI is installed and used for the first time, the UI tries to automatically set `project_path`, `helmet_scripts_path`, and `emme_python_path`. How should we take this into consideration?
- Command-line interface was changed in `helmet-model-system-v4.1` compared to `v4.0`. The UI does not fully support running `v4.0` anymore but it is possible.

**Comment by zptro** [comment]
We should discuss this in more detail later, but I would definitely prefer keeping some settings (e.g., `basedata_path`) on project level, hence not bringing them all down to scenario level. I would say it would be nice if only scenarios of one project at a time would be visible in the scenario list (so it is clear that they all belong to that very project), but maybe we could allow scenarios from several project to be chosen for running? Need to brainstorm about this!

**Comment by johpiip** [comment]
Idea: lisätään "Projektin asetukset" myös skenaarioasetusten loppuun, jossa valittuja asetuksia voi ajaa yli skenaariokohtaisilla asetuksilla. Pitää näkyä visuaalisesti, että mitkä asetukset ovat edelleen oletusarvoilla.

**Comment by e-halinen** [comment]
Tweak the styling of default project setting values (more like placeholder style), remove the override toggle
