### ISSUE TITLE
What does us2 do?

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-ui#155]
@eevavesaoja :n jatkokysymys https://github.com/HSLdevcom/helmet-ui/pull/145 :ssä:

Voisi selostaa mitä us2-skripti tekee pääpiirteissään? (jos ei ymmärrä python-skriptiä)

_Originally posted by @eevavesaoja in https://github.com/HSLdevcom/helmet-ui/pull/145#pullrequestreview-1189610335_

**Comment by zptro** [comment]
Eli tässä:

https://github.com/HSLdevcom/helmet-ui/blob/f5b0363090f37df741806320417531c132ae79eb/docs/emme_verkko.md?plain=1#L591

Skriptin toiminnallisuus on kuvattu sivulla 91 (7.5.2 Joukkoliikenteen viivytysfunktiot) tässä raportissa:

https://hslfi.azureedge.net/globalassets/julkaisuarkisto/2019/helsingin-seudun-tyossakayntialueen-liikenne-ennustejarjestelman-tarjontamallit-6-2019.pdf

**Comment by johpiip** [comment]
Kiitos @zptro, tuli pyytämättä ja yllättäen! 😃
