### ISSUE TITLE
Scenario duplication

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/helmet-ui#169]
Wish from user #1 

Idea - it should be possible to duplicate a scenario so that it can be slightly altered via UI. Should duplicate the folders as needed for the run. To be further clarified.

**Comment by johpiip** [comment]
Just a small point: your hashtag makes the number refer to an issue. 😄

**Comment by johpiip** [comment]
Could be an icon next to "edit" and "remove" that means duplication.

**Comment by e-halinen** [comment]
Duplicated scenario should have number "(1)" added into the name to implicate duplicate values
