### ISSUE TITLE
Add link to the Results folder for each scenario

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/helmet-ui#172]

**Comment by johpiip** [comment]
Opens a file explorer. Result folder is always a local folder (result-forlder parameter + scenario-name)

**Comment by johpiip** [comment]
Could be next to "lokit" when a model run is finished. Maybe consider a corner case where the model run end in an error?


![Image](https://github.com/HSLdevcom/helmet-ui/assets/20718745/e32c4e43-4876-48f2-a0d4-5a897bb8856d)
