### ISSUE TITLE
Show settings for each scenario by hovering over it.

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/helmet-ui#173]

**Comment by hsl-petrhaj** [comment]
Lower priority - could reuse the feature from scenarios before running.

**Comment by johpiip** [comment]
Ideas:
- a summary of options, not everything
- same option dialogues can open during model run but they are "grey read-only"

**Comment by hsl-petrhaj** [comment]
chosen settings:
emme_path (shortened)
forecast_scenario_id
forecast_data_path (shortened)
save_matrices_in_emme
end_assignment_only

global setting, if it has changed
