### ISSUE TITLE
Update HSL Code Signing certificate

### ISSUE THREAD

**Issue by johpiip** [HSLdevcom/helmet-ui#174]
I received a new certificate 11.4.2023 from Enfo and it is viable for 3 years. It is a pfx file.

**Comment by hsl-petrhaj** [comment]
How to implement it? Do we need to send it to Teemu?

**Comment by johpiip** [comment]
I don't want to write details here as I don't know how sensitive this is. 😄

**Comment by johpiip** [comment]
Minä hoidan!

**Comment by johpiip** [comment]
Works now, Helsingin seudun liikenne-kuntayhtymä shows as publisher:
![kuva](https://github.com/HSLdevcom/helmet-ui/assets/20718745/455ce035-7cc2-4387-aa22-9fa5e866360f)

And details look okay to me:
![kuva](https://github.com/HSLdevcom/helmet-ui/assets/20718745/db642c49-749d-4536-b57f-a3df5fafe67d)
