### ISSUE TITLE
Add visible link to helmet-docs to the bottom of the UI

### ISSUE THREAD

**Issue by hsl-petrhaj** [HSLdevcom/helmet-ui#175]
Should not be screaming at the user, but should be visible all the time.

**Comment by johpiip** [comment]
Another idea: add an icon somewhere in header which links to helmet-docs (https://hsldevcom.github.io/helmet-docs/)

**Comment by johpiip** [comment]
I will search Helmet UI Figma layouts.

**Comment by e-halinen** [comment]
Proposed icon to add to the app header:
https://tyyliopas.hsl.fi/d/h8JR9dHeqfgd/piktogrammikirjasto/show/eyJpZCI6NTA3MDgzOCwidGltZXN0YW1wIjoiMTY4NTU5OTI2MiJ9:frontify:W4FVErp4eUa9sL4HAR02r8RSMGZs7nv0VyZSWHyAW8A

Taken from here: https://tyyliopas.hsl.fi/d/h8JR9dHeqfgd/piktogrammikirjasto

**Comment by e-halinen** [comment]
Move the icon to the left, change from "book" to "info" icon: https://tyyliopas.hsl.fi/d/h8JR9dHeqfgd/piktogrammikirjasto/show/eyJpZCI6NTA3MDk1MSwidGltZXN0YW1wIjoiMTY4NjY0MjI3NiJ9:frontify:j2Ua8TM2Qc8H96Hv4u7bKRiVLN4ozj0ORLeYyPu_xKM
