### ISSUE TITLE
UI crashes if Scripts folder is relocated 

### ISSUE THREAD

**Issue by atte-wsp** [HSLdevcom/helmet-ui#19]
Moved the "helmet-model-system/Scripts" and "Project" folders to different location, which caused the UI to crash and show only blank window to user. I had already used UI to run helmet-model-system, so these parameters pointed to old folder locations. 

The problem was fixed by copying the folders back to their initial place, after which I could open the UI and set the folder path to new location. Reinstalling UI would not fix the issue.

**Comment by johpiip** [comment]
I was able to reproduce this via moving "Projektin kansiopolku" but not "HELMET model-system" (aka Script folder).

1. Open UI.
1. Set "Projektin kansiopolku"
1. Close UI.
1. Move "Projektin kansiopolku" folder to another location.
1. When trying to open UI again, it should only show a blank screen and maybe some flickering.
