### ISSUE TITLE
Log of used input files for each model run

### ISSUE THREAD

**Issue by zptro** [HSLdevcom/helmet-ui#4]
Save used input files somewhere in connection to results.

**Comment by zptro** [comment]
Alternatively only save the names of used input files.

**Comment by Mew-www** [comment]
Which input files, the forecast zonedata ("data folder") or also base_zonedata & base_matrices?

Also, wouldn't this be part of model-system rather than UI, if it involves results?

**Comment by zptro** [comment]
This is logged rather good nowadays.
