### ISSUE TITLE
Runtime results: Convergence, KPIs, etc

### ISSUE THREAD

**Issue by zptro** [HSLdevcom/helmet-ui#6]
Print both during runtime and more detailed in the end.

**Comment by zptro** [comment]
Format for end results? CSV or similar

**Comment by Mew-www** [comment]
As the issue #4 , doesn't this more relate to model-system (as a functionality, which would then be displayed in UI)?

**Comment by hsl-petrhaj** [comment]
Notes: 
1) Print model run times
2) Demand convergence into a plot (x-axis iteration, y-axis max_gap or rel_gap) -> Replace the bar with live plot, updated once per iteration. 
3) Iteration loading bar shows for example 2/15, but we rarely run all the way to 15. "Max 15" -> Remove the whole bar (perhaps?)

**Comment by hsl-petrhaj** [comment]
Check if starting time is in logs. If not, model system should provide it.
