### ISSUE TITLE
Lähtötietojen jakoaineistojen metatietojen tarkistus

### ISSUE THREAD

**Issue by eevavesaoja** [HSLdevcom/helmet-ui#79]
Onko kaikissa jakokansioissa yhtenevät ja riittävät metatiedot (readme tms)? Olisi hyvä käydä systemaattisesti läpi
Esim. Emme-koulutuksen yhteydessä ladatun Ennusteskenaarioiden syöttötiedot -kansion tiedostoissa ei ole kuvattu mistä tiedot ovat peräisin (esim. MAL-työ 2019 tms)

**Comment by zptro** [comment]
Kuvataan suoraan tiedostoihin
