### ISSUE TITLE
Ohjeiden ja jaettavien aineistojen selkeytys

### ISSUE THREAD

**Issue by eevavesaoja** [HSLdevcom/helmet-ui#80]
Suuri osa lähtötiedoista ladataan omana pakettinaan (mm. maankäyttö, verkko), mutta osa (mm. kulkutavat, funktiot) latautuu Helmet-makrojen yhteydessä, jotka on ohjeistettu erikseen. Kannattaisiko kaikki lähtötiedot koota yhteen ja samaan latausaineistoon ja pelkät makrot toisena omana pakettinaan? Makrojen osalta voisi lisäksi erotella mallin ajon kannalta välttämättömät makrot ja työskentelyä helpottavat makrot ja selkiyttää näiden ohjeistusta (mm. Miten ja kenen on tarkoitus hyödyntää tarkista-makroa? Verkkojen sisäänajomakro ajaa tarkistusmakron, mutta tuloksia ei taideta käyttää? Olisiko tarvetta hyödyntää makroa laajemmin ja ohjeistaa sitä?). Muita makroja listattu sivun sijopankki.md lopussa.

Liittyy osittain myös toiseen issueen tuoreiden käyttäjien ohjeesta muokatuilla lähtötiedoilla ajoon.

**Comment by zptro** [comment]
Mallia voidaan testata pienellä testiverkolla ja -maankäyttödatalla, jotka eivät vaadi käyttöluvan hakemista. Kulkutavat ja funktiot (ja em. testidatat) ovat githubissa, koska niitä tarvitaan näihin testeihin.

Makroista on tarkoitus päästä kokonaan eroon vielä tänä vuonna.
