### ISSUE TITLE
The helmet icon is not assigned

### ISSUE THREAD

**Issue by zptro** [HSLdevcom/helmet-ui#98]
This should add the helmet icon:
https://github.com/HSLdevcom/helmet-ui/blob/534601f3dc9c8dbc8d08516bee1dc55042dcfd10/forge-config.js#L21

Instead the app uses the electron icon.

**Comment by zptro** [comment]
There is also a `setupIcon` configuration. If that is set, app installation crashes.

**Comment by johpiip** [comment]
I will open this issue so that we can maybe both test that the icon shows. The icons have had some weird errors in the past.
